- Celest you nut, you didn't add grfio.* to common/, only removed them from map/ :X - I am guessing more files are missing, because there's also an undefined reference to zlib_init.... >.> - Ya forgot to add the files, didn't ya?